fixtures:
  forge_modules:
    choria: "choria/mcollective_choria"
    stdlib: "puppetlabs/stdlib"
    apt: "puppetlabs/apt"
    translate: "puppetlabs/translate"
    yumrepo: "puppetlabs/yumrepo_core"
