version: 2
jobs:
  puppetlabs_spec_ruby24:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
  puppetlabs_spec_ruby25:
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
  puppetlabs_spec_ruby27:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
  puppetlabs_spec_ruby3:
    docker:
      - image: circleci/ruby:3.0-node
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - puppetlabs_spec_ruby24
      - puppetlabs_spec_ruby25
      - puppetlabs_spec_ruby27
      - puppetlabs_spec_ruby3
