---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  global_env: 
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  dist: trusty
  deploy_to_forge:
    enabled: false
  branches:
  - release
  user: puppet
  secure: ''
  use_litmus: true
  litmus:
    provision_list:
      - travis_deb
      - travis_ub
      - travis_el6
      - travis_el7
      - travis_el8
      - ---travis_el
  simplecov: true
  notifications:
    slack:
      secure: >-
        Bi6bwC7CEQ+XcmpUfv68i0bQ5l8PBCGRs3DDvspbC9wF/gZnY1xQJj/w4wKx0CrGyYcOJ6rrJUOwn1ES628FwMRhccNs9JVJaxujEucl7IrQ8Xzn0567/p8vE7YkjRnjUFkuZ5CgUMPBdU+NczyP+CNYNBkGyj/tvDyLX6UZOXKstf5PoFwR0xZdCE0CHm9sQ+eh4Ui+9SV0V0nDY8CpSA4injmVWR1Kk2Rw+RkQCUruR8VDpEPsiVocaDK+4SPub6RBQdL6PkIGiV2/2Ya0mXPGoL4LKgdrBJM+IscFbSakEAQOvQSMBgMteS0PYo09vNzojjAxQgxWDvaPjAw+3hZT4nCi444EKCU5bV8JcCxHDm0cF9lhCzy1YShGqmIGPX2j8suYYg9/vjo5sHaF5i+FaVtF2wE6t7atGJ99xYHd1Zpww0LgYUCeif5vDITJ49K6wivsLtPIZ/Jl++nBVduKZ1YPwsceDZU4xwJ3+YZ9SnhQZFFbI6lER+Gc5g7DnGPruMecY5kofkCTom9XcM4/AHTZOK0EadX1U88lGwNI8j5ak7TsIQTplQmGeJuVQ2qgoefiqUgmPRgj0YlJ+eWVEKrXZ7htVmgXJ9KOdswnSKNElbbhU4u52BEkG0coAaOhSW/EiVpmMGaOCkpDXWKy14pZMPVmTK3swOYCqG4=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  use_litmus: true
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  simplecov: true
Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
Rakefile:
  requires:
  - puppet_pot_generator/rake_tasks
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
